### ISSUE TITLE
ConcentratedLiquidityPool Missing

### ISSUE THREAD

**Issue by owenshen24** [sushiswap/trident#123]
Howdy,

The link to ConcentratedLiquidityPool via `trident/blob/master/contracts/pool/concentrated/ConcentratedLiquidityPool.sol` doesn't seem to lead to a valid file.

Is this code forthcoming?

**Comment by Ro5s** [comment]
heya @owenshen24, we are currently working on that pool type in a [separate branch](https://github.com/sushiswap/trident/tree/concentrated/contracts/pool/concentrated) and the link in readme is placeholder for merge.

**Comment by owenshen24** [comment]
Ahhhh, ty for the heads-up!
