### ISSUE TITLE
../tasks/add-liquidity.ts:2:80 - error TS2307: Cannot find module '../types' or its corresponding type declarations.  2 import type { BentoBoxV1, BentoBoxV1__factory, ERC20Mock, TridentRouter } from "../types"

### ISSUE THREAD

**Issue by EngineEarz** [sushiswap/trident#353]
../tasks/add-liquidity.ts:2:80 - error TS2307: Cannot find module '../types' or its corresponding type declarations.

2 import type { BentoBoxV1, BentoBoxV1__factory, ERC20Mock, TridentRouter } from "../types"

**Comment by matthewlilley** [comment]
yarn build
